<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\HusayniaSMS.Core\HusayniaSMS.Core.csproj" />
    <PackageReference Include="CsvHelper" />
    <PackageReference Include="Microsoft.Bcl.Memory" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" />
    <PackageReference Include="Twilio" />
  </ItemGroup>
</Project>