// <auto-generated />
using System;
using HusayniaTabruk.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable IDE0161
#pragma warning disable CA1861

namespace HusayniaTabruk.Infrastructure.Migrations
{
    [DbContext(typeof(TabrukDbContext))]
    [Migration("20260815075156_InitialPostgresSchema")]
    partial class InitialPostgresSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HusayniaTabruk.Infrastructure.Identity.Entities.TabrukIdentityUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("HusayniaTabruk.Infrastructure.Persistence.Entities.AuditEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_membership_id");

                    b.Property<string>("AfterState")
                        .HasColumnType("text")
                        .HasColumnName("after_state");

                    b.Property<string>("BeforeState")
                        .HasColumnType("text")
                        .HasColumnName("before_state");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("purpose");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("resource_type");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "ActorMembershipId");

                    b.HasIndex("OrganizationId", "OccurredAt");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("HusayniaTabruk.Infrastructure.Persistence.Entities.DateThreadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("LockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("ServiceDateId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_date_id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ServiceDateId")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "ServiceDateId");

                    b.ToTable("date_threads", null, t =>
                        {
                            t.HasCheckConstraint("ck_date_threads_lock_state", "(\"status\" = 0 AND \"locked_at\" IS NULL) OR (\"status\" = 1 AND \"locked_at\" IS NOT NULL)");

                            t.HasCheckConstraint("ck_date_threads_version_nonnegative", "\"version\" >= 0");
                        });
                });

            modelBuilder.Entity("HusayniaTabruk.Infrastructure.Persistence.Entities.DeviceRegistrationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("uuid")
                        .HasColumnName("installation_id");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("membership_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("platform");

                    b.Property<string>("ProviderToken")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("provider_token");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "MembershipId", "InstallationId")
                        .IsUnique();

                    b.ToTable("device_registrations", (string)null);
                });

            modelBuilder.Entity("HusayniaTabruk.Infrastructure.Persistence.Entities.HelpNeedEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<short>("Category")
                        .HasColumnType("smallint")
                        .HasColumnName("category");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("instructions");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("ServiceDateId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_date_id");

                    b.Property<long>("SignupVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("signup_version");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<long>("WaitlistOrderHighWater")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("waitlist_order_high_water");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id");

                    b.HasIndex("ServiceDateId", "Category")
                        .IsUnique();

                    b.ToTable("help_needs", null, t =>
                        {
                            t.HasCheckConstraint("ck_help_needs_capacity", "\"capacity\" IS NULL OR \"capacity\" > 0");

                            t.HasCheckConstraint("ck_help_needs_category", "\"category\" IN (0, 1, 2)");

                            t.HasCheckConstraint("ck_help_needs_status", "\"status\" IN (0, 1)");

                            t.HasCheckConstraint("ck_help_needs_version", "\"version\" >= 0 AND \"signup_version\" >= 0");

                            t.HasCheckConstraint("ck_help_needs_waitlist_order_high_water", "\"waitlist_order_high_water\" >= 0");
                        });
                });

            modelBuilder.Entity("HusayniaTabruk.Infrastructure.Persistence.Entities.IdempotencyRecordEntity", b =>
                {
                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("membership_id");

                    b.Property<Guid>("Key")
                        .HasColumnType("uuid")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("operation");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("request_fingerprint")
                        .IsFixedLength();

                    b.Property<string>("ResultReference")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("result_reference");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.HasKey("OrganizationId", "MembershipId", "Key");

                    b.HasIndex("OrganizationId", "ExpiresAt");

                    b.ToTable("idempotency_records", null, t =>
                        {
                            t.HasCheckConstraint("ck_idempotency_records_expiry", "\"expires_at\" > \"created_at\"");

                            t.HasCheckConstraint("ck_idempotency_records_result", "(\"status\" = 1 AND \"result_reference\" IS NOT NULL) OR (\"status\" IN (0, 2) AND \"result_reference\" IS NULL)");

                            t.HasCheckConstraint("ck_idempotency_records_status", "\"status\" IN (0, 1, 2)");
                        });
                });

            modelBuilder.Entity("HusayniaTabruk.Infrastructure.Persistence.Entities.InvitationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<Guid>("IssuedByMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("issued_by_membership_id");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "IssuedByMembershipId");

                    b.HasIndex("OrganizationId", "NormalizedEmail");

                    b.ToTable("invitations", null, t =>
                        {
                            t.HasCheckConstraint("ck_invitations_accept_revoke", "\"accepted_at\" IS NULL OR \"revoked_at\" IS NULL");

                            t.HasCheckConstraint("ck_invitations_expiry", "\"expires_at\" > \"issued_at\"");
                        });
                });

            modelBuilder.Entity("HusayniaTabruk.Infrastructure.Persistence.Entities.MembershipEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("EligibleAsNamedParticipant")
                        .HasColumnType("boolean")
                        .HasColumnName("eligible_as_named_participant");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("OrganizationId", "UserId")
                        .IsUnique();

                    b.ToTable("memberships", null, t =>
                        {
                            t.HasCheckConstraint("ck_memberships_status", "\"status\" IN (0, 1, 2)");
                        });
                });

            modelBuilder.Entity("HusayniaTabruk.Infrastructure.Persistence.Entities.MessageReportEntity", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<Guid>("ReporterMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("reporter_membership_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comment");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<short>("Reason")
                        .HasColumnType("smallint")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("ReportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reported_at");

                    b.Property<short>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("state");

                    b.HasKey("MessageId", "ReporterMembershipId");

                    b.HasIndex("OrganizationId", "MessageId");

                    b.HasIndex("OrganizationId", "ReportedAt");

                    b.HasIndex("OrganizationId", "ReporterMembershipId");

                    b.ToTable("message_reports", null, t =>
                        {
                            t.HasCheckConstraint("ck_message_reports_reason", "\"reason\" IN (0, 1, 2, 3)");

                            t.HasCheckConstraint("ck_message_reports_state", "\"state\" = 0");
                        });
                });

            modelBuilder.Entity("HusayniaTabruk.Infrastructure.Persistence.Entities.NotificationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<Guid>("RecipientMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_membership_id");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<short>("ResourceType")
                        .HasColumnType("smallint")
                        .HasColumnName("resource_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "RecipientMembershipId", "ReadAt", "CreatedAt");

                    b.ToTable("notifications", null, t =>
                        {
                            t.HasCheckConstraint("ck_notifications_read_chronology", "\"read_at\" IS NULL OR \"read_at\" >= \"created_at\"");

                            t.HasCheckConstraint("ck_notifications_resource_type", "\"resource_type\" IN (0, 1, 2, 3)");

                            t.HasCheckConstraint("ck_notifications_type", "\"type\" IN (0, 1, 2, 3)");
                        });
                });

            modelBuilder.Entity("HusayniaTabruk.Infrastructure.Persistence.Entities.OrganizationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("BootstrapSealedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bootstrap_sealed_at");

                    b.Property<short>("BootstrapStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("bootstrap_status");

                    b.Property<int>("DefaultCancellationLeadMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("default_cancellation_lead_minutes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("organizations", null, t =>
                        {
                            t.HasCheckConstraint("ck_organizations_bootstrap_state", "(\"bootstrap_status\" = 0 AND \"bootstrap_sealed_at\" IS NULL) OR (\"bootstrap_status\" = 1 AND \"bootstrap_sealed_at\" IS NOT NULL)");

                            t.HasCheckConstraint("ck_organizations_version_nonnegative", "\"version\" >= 0");
                        });
                });

            modelBuilder.Entity("HusayniaTabruk.Infrastructure.Persistence.Entities.OutboxMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset?>("DeadLetteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dead_lettered_at");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ProcessedAt", "DeadLetteredAt", "NextAttemptAt");

                    b.ToTable("outbox_messages", null, t =>
                        {
                            t.HasCheckConstraint("ck_outbox_messages_attempts", "\"attempts\" >= 0");
                        });
                });

            modelBuilder.Entity("HusayniaTabruk.Infrastructure.Persistence.Entities.PrivilegedAccessEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_membership_id");

                    b.Property<string>("CaseId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("case_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PageCursor")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("page_cursor");

                    b.Property<string>("PageHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("page_hash")
                        .IsFixedLength();

                    b.Property<short>("Purpose")
                        .HasColumnType("smallint")
                        .HasColumnName("purpose");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("resource_type");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "ActorMembershipId", "OccurredAt");

                    b.ToTable("privileged_access_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_privileged_access_events_purpose", "\"purpose\" IN (0, 1, 2)");
                        });
                });

            modelBuilder.Entity("HusayniaTabruk.Infrastructure.Persistence.Entities.RoleAssignmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid>("AssignedByMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by_membership_id");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("membership_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid?>("RevokedByMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("revoked_by_membership_id");

                    b.Property<short>("Role")
                        .HasColumnType("smallint")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "AssignedByMembershipId");

                    b.HasIndex("OrganizationId", "RevokedByMembershipId");

                    b.HasIndex("OrganizationId", "MembershipId", "Role")
                        .IsUnique()
                        .HasDatabaseName("ux_role_assignments_active")
                        .HasFilter("\"revoked_at\" IS NULL");

                    b.ToTable("role_assignments", null, t =>
                        {
                            t.HasCheckConstraint("ck_role_assignments_revocation", "(\"revoked_at\" IS NULL AND \"revoked_by_membership_id\" IS NULL) OR (\"revoked_at\" IS NOT NULL AND \"revoked_by_membership_id\" IS NOT NULL)");

                            t.HasCheckConstraint("ck_role_assignments_role", "\"role\" IN (0, 1)");
                        });
                });

            modelBuilder.Entity("HusayniaTabruk.Infrastructure.Persistence.Entities.RoleChangeRequestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("Action")
                        .HasColumnType("smallint")
                        .HasColumnName("action");

                    b.Property<string>("AfterState")
                        .HasColumnType("text")
                        .HasColumnName("after_state");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApproverMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("approver_membership_id");

                    b.Property<string>("BeforeState")
                        .HasColumnType("text")
                        .HasColumnName("before_state");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset>("ProposedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("proposed_at");

                    b.Property<Guid>("ProposerMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("proposer_membership_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("TargetMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_membership_id");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "ApproverMembershipId");

                    b.HasIndex("OrganizationId", "ProposerMembershipId");

                    b.HasIndex("OrganizationId", "TargetMembershipId");

                    b.HasIndex("OrganizationId", "Status", "ExpiresAt");

                    b.ToTable("role_change_requests", null, t =>
                        {
                            t.HasCheckConstraint("ck_role_change_requests_action", "\"action\" IN (0, 1)");

                            t.HasCheckConstraint("ck_role_change_requests_approval_state", "(\"status\" = 0 AND \"approver_membership_id\" IS NULL AND \"approved_at\" IS NULL) OR (\"status\" = 1 AND \"approver_membership_id\" IS NOT NULL AND \"approved_at\" IS NOT NULL)");

                            t.HasCheckConstraint("ck_role_change_requests_participants", "\"proposer_membership_id\" <> \"target_membership_id\" AND (\"approver_membership_id\" IS NULL OR (\"approver_membership_id\" <> \"proposer_membership_id\" AND \"approver_membership_id\" <> \"target_membership_id\"))");

                            t.HasCheckConstraint("ck_role_change_requests_status", "\"status\" IN (0, 1)");

                            t.HasCheckConstraint("ck_role_change_requests_timing", "\"expires_at\" = \"proposed_at\" + INTERVAL '24 hours' AND (\"approved_at\" IS NULL OR (\"approved_at\" >= \"proposed_at\" AND \"approved_at\" < \"expires_at\"))");
                        });
                });

            modelBuilder.Entity("HusayniaTabruk.Infrastructure.Persistence.Entities.ServiceDateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CancellationDeadlineAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancellation_deadline_at");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("instructions");

                    b.Property<Guid>("ManagerMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("manager_membership_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "ManagerMembershipId");

                    b.HasIndex("OrganizationId", "Status", "StartsAt");

                    b.ToTable("service_dates", null, t =>
                        {
                            t.HasCheckConstraint("ck_service_dates_chronology", "\"starts_at\" < \"ends_at\" AND \"cancellation_deadline_at\" <= \"starts_at\"");

                            t.HasCheckConstraint("ck_service_dates_status", "\"status\" IN (0, 1, 2, 3, 4)");

                            t.HasCheckConstraint("ck_service_dates_version", "\"version\" >= 0");
                        });
                });

            modelBuilder.Entity("HusayniaTabruk.Infrastructure.Persistence.Entities.SignupEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("HelpNeedId")
                        .HasColumnType("uuid")
                        .HasColumnName("help_need_id");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<string>("Label")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("label");

                    b.Property<DateTimeOffset?>("LastTransitionAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_transition_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("PrimaryMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("primary_membership_id");

                    b.Property<Guid>("ServiceDateId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_date_id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<int>("UnnamedParticipantCount")
                        .HasColumnType("integer")
                        .HasColumnName("unnamed_participant_count");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<long?>("WaitlistOrder")
                        .HasColumnType("bigint")
                        .HasColumnName("waitlist_order");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "PrimaryMembershipId");

                    b.HasIndex("HelpNeedId", "Status", "WaitlistOrder");

                    b.HasIndex("OrganizationId", "HelpNeedId", "PrimaryMembershipId")
                        .IsUnique()
                        .HasDatabaseName("ux_signups_active_primary_per_help_need")
                        .HasFilter("\"status\" IN (0, 1, 2)");

                    b.HasIndex("OrganizationId", "ServiceDateId", "HelpNeedId");

                    b.ToTable("signups", null, t =>
                        {
                            t.HasCheckConstraint("ck_signups_kind", "\"kind\" IN (0, 1, 2)");

                            t.HasCheckConstraint("ck_signups_label_unicode_scalars", "\"label\" IS NULL OR char_length(\"label\") <= 80");

                            t.HasCheckConstraint("ck_signups_label_utf8_bytes", "\"label\" IS NULL OR octet_length(convert_to(\"label\", 'UTF8')) <= 320");

                            t.HasCheckConstraint("ck_signups_state_metadata", "(\"status\" = 0 AND \"last_transition_at\" IS NULL AND \"waitlist_order\" IS NULL) OR (\"status\" = 2 AND \"last_transition_at\" IS NOT NULL AND \"waitlist_order\" > 0) OR (\"status\" IN (1, 3, 4, 5) AND \"last_transition_at\" IS NOT NULL AND \"waitlist_order\" IS NULL)");

                            t.HasCheckConstraint("ck_signups_status", "\"status\" IN (0, 1, 2, 3, 4, 5)");

                            t.HasCheckConstraint("ck_signups_unnamed_participants", "\"unnamed_participant_count\" >= 0");

                            t.HasCheckConstraint("ck_signups_version", "\"version\" >= 0");
                        });
                });

            modelBuilder.Entity("HusayniaTabruk.Infrastructure.Persistence.Entities.SignupMemberParticipantEntity", b =>
                {
                    b.Property<Guid>("SignupId")
                        .HasColumnType("uuid")
                        .HasColumnName("signup_id");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("membership_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("SignupId", "MembershipId");

                    b.HasIndex("OrganizationId", "MembershipId");

                    b.HasIndex("OrganizationId", "SignupId");

                    b.ToTable("signup_member_participants", (string)null);
                });

            modelBuilder.Entity("HusayniaTabruk.Infrastructure.Persistence.Entities.ThreadMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_membership_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("body");

                    b.Property<Guid>("ClientMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_message_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("HiddenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hidden_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uuid")
                        .HasColumnName("thread_id");

                    b.Property<short>("Visibility")
                        .HasColumnType("smallint")
                        .HasColumnName("visibility");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "AuthorMembershipId");

                    b.HasIndex("OrganizationId", "ThreadId");

                    b.HasIndex("ThreadId", "ClientMessageId")
                        .IsUnique();

                    b.ToTable("thread_messages", null, t =>
                        {
                            t.HasCheckConstraint("ck_thread_messages_visibility", "(\"visibility\" = 0 AND \"hidden_at\" IS NULL) OR (\"visibility\" = 1 AND \"hidden_at\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("HusayniaTabruk.Infrastructure.Persistence.Entities.ThreadModerationEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorMembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_membership_id");

                    b.Property<Guid?>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uuid")
                        .HasColumnName("thread_id");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "ActorMembershipId");

                    b.HasIndex("OrganizationId", "MessageId");

                    b.HasIndex("OrganizationId", "ThreadId");

                    b.HasIndex("ThreadId", "OccurredAt");

                    b.ToTable("thread_moderation_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_thread_moderation_events_action", "\"action\" IN ('hide', 'lock')");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("identity_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("identity_role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("identity_user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("identity_user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("identity_user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("identity_user_tokens", (string)null);
                });

            modelBuilder.Entity("HusayniaTabruk.Infrastructure.Persistence.Entities.AuditEventEntity", b =>
                {
                    b.HasOne("HusayniaTabruk.Infrastructure.Persistence.Entities.MembershipEntity", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ActorMembershipId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HusayniaTabruk.Infrastructure.Persistence.Entities.DateThreadEntity", b =>
                {
                    b.HasOne("HusayniaTabruk.Infrastructure.Persistence.Entities.ServiceDateEntity", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ServiceDateId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HusayniaTabruk.Infrastructure.Persistence.Entities.DeviceRegistrationEntity", b =>
                {
                    b.HasOne("HusayniaTabruk.Infrastructure.Persistence.Entities.MembershipEntity", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "MembershipId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HusayniaTabruk.Infrastructure.Persistence.Entities.HelpNeedEntity", b =>
                {
                    b.HasOne("HusayniaTabruk.Infrastructure.Persistence.Entities.ServiceDateEntity", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ServiceDateId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HusayniaTabruk.Infrastructure.Persistence.Entities.IdempotencyRecordEntity", b =>
                {
                    b.HasOne("HusayniaTabruk.Infrastructure.Persistence.Entities.MembershipEntity", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "MembershipId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HusayniaTabruk.Infrastructure.Persistence.Entities.InvitationEntity", b =>
                {
                    b.HasOne("HusayniaTabruk.Infrastructure.Persistence.Entities.OrganizationEntity", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HusayniaTabruk.Infrastructure.Persistence.Entities.MembershipEntity", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "IssuedByMembershipId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HusayniaTabruk.Infrastructure.Persistence.Entities.MembershipEntity", b =>
                {
                    b.HasOne("HusayniaTabruk.Infrastructure.Persistence.Entities.OrganizationEntity", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HusayniaTabruk.Infrastructure.Identity.Entities.TabrukIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HusayniaTabruk.Infrastructure.Persistence.Entities.MessageReportEntity", b =>
                {
                    b.HasOne("HusayniaTabruk.Infrastructure.Persistence.Entities.ThreadMessageEntity", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "MessageId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HusayniaTabruk.Infrastructure.Persistence.Entities.MembershipEntity", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ReporterMembershipId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HusayniaTabruk.Infrastructure.Persistence.Entities.NotificationEntity", b =>
                {
                    b.HasOne("HusayniaTabruk.Infrastructure.Persistence.Entities.MembershipEntity", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "RecipientMembershipId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HusayniaTabruk.Infrastructure.Persistence.Entities.OutboxMessageEntity", b =>
                {
                    b.HasOne("HusayniaTabruk.Infrastructure.Persistence.Entities.OrganizationEntity", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HusayniaTabruk.Infrastructure.Persistence.Entities.PrivilegedAccessEventEntity", b =>
                {
                    b.HasOne("HusayniaTabruk.Infrastructure.Persistence.Entities.MembershipEntity", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ActorMembershipId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HusayniaTabruk.Infrastructure.Persistence.Entities.RoleAssignmentEntity", b =>
                {
                    b.HasOne("HusayniaTabruk.Infrastructure.Persistence.Entities.MembershipEntity", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "AssignedByMembershipId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HusayniaTabruk.Infrastructure.Persistence.Entities.MembershipEntity", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "MembershipId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HusayniaTabruk.Infrastructure.Persistence.Entities.MembershipEntity", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "RevokedByMembershipId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HusayniaTabruk.Infrastructure.Persistence.Entities.RoleChangeRequestEntity", b =>
                {
                    b.HasOne("HusayniaTabruk.Infrastructure.Persistence.Entities.OrganizationEntity", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HusayniaTabruk.Infrastructure.Persistence.Entities.MembershipEntity", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ApproverMembershipId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HusayniaTabruk.Infrastructure.Persistence.Entities.MembershipEntity", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ProposerMembershipId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HusayniaTabruk.Infrastructure.Persistence.Entities.MembershipEntity", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "TargetMembershipId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HusayniaTabruk.Infrastructure.Persistence.Entities.ServiceDateEntity", b =>
                {
                    b.HasOne("HusayniaTabruk.Infrastructure.Persistence.Entities.OrganizationEntity", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HusayniaTabruk.Infrastructure.Persistence.Entities.MembershipEntity", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ManagerMembershipId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HusayniaTabruk.Infrastructure.Persistence.Entities.SignupEntity", b =>
                {
                    b.HasOne("HusayniaTabruk.Infrastructure.Persistence.Entities.MembershipEntity", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "PrimaryMembershipId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HusayniaTabruk.Infrastructure.Persistence.Entities.ServiceDateEntity", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ServiceDateId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HusayniaTabruk.Infrastructure.Persistence.Entities.HelpNeedEntity", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ServiceDateId", "HelpNeedId")
                        .HasPrincipalKey("OrganizationId", "ServiceDateId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HusayniaTabruk.Infrastructure.Persistence.Entities.SignupMemberParticipantEntity", b =>
                {
                    b.HasOne("HusayniaTabruk.Infrastructure.Persistence.Entities.MembershipEntity", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "MembershipId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HusayniaTabruk.Infrastructure.Persistence.Entities.SignupEntity", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "SignupId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HusayniaTabruk.Infrastructure.Persistence.Entities.ThreadMessageEntity", b =>
                {
                    b.HasOne("HusayniaTabruk.Infrastructure.Persistence.Entities.MembershipEntity", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "AuthorMembershipId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HusayniaTabruk.Infrastructure.Persistence.Entities.DateThreadEntity", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ThreadId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HusayniaTabruk.Infrastructure.Persistence.Entities.ThreadModerationEventEntity", b =>
                {
                    b.HasOne("HusayniaTabruk.Infrastructure.Persistence.Entities.MembershipEntity", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ActorMembershipId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HusayniaTabruk.Infrastructure.Persistence.Entities.ThreadMessageEntity", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "MessageId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HusayniaTabruk.Infrastructure.Persistence.Entities.DateThreadEntity", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ThreadId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("HusayniaTabruk.Infrastructure.Identity.Entities.TabrukIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("HusayniaTabruk.Infrastructure.Identity.Entities.TabrukIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HusayniaTabruk.Infrastructure.Identity.Entities.TabrukIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("HusayniaTabruk.Infrastructure.Identity.Entities.TabrukIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
